version: '3.1'

services:

  database:
    image: postgres
    restart: always
    volumes:
      -  ~/docker/database:/var/lib/postgres/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432

  search:
    image: getmeili/meilisearch
    restart: always
    volumes:
      - ~/docker/data.ms:/data.ms
    ports:
      - 7700:7700